# -*- coding: utf-8 -*-
"""Pandas 612.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14mMqUCr2mmRth8Xdj4wbTXPrlH9gyW3q
"""

import pandas as pd

data={
    "Familiya":["Qadamova","Aliyev"],
    "Ism":["Zulayho","Ali"],
    "Yoshi":[29,31],
    "Manzili":["Farg'ona shaxar","Qo'qon shaxar"],
    "Kursi":["bitirgan","2- kurs"],
    "Jinsi":["Ayol","Erkak"]
}
baza=pd.DataFrame(data)
print(baza)

filtr=baza[baza["Yoshi"]<30]
print(filtr)

filtr=baza[baza["Manzili"]=="Qo'qon shaxar"]
print(filtr)

pd.read_csv("titanic.csv")